# Logging Configuration

version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s:%(funcName)s:%(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/yunmin_pipeline.log
    mode: a

  error_file:
    class: logging.FileHandler
    level: ERROR
    formatter: detailed
    filename: logs/errors.log
    mode: a

  phase_file:
    class: logging.FileHandler
    level: INFO
    formatter: default
    filename: logs/phase_execution.log
    mode: a

loggers:
  yunmin:
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: false
  
  yunmin.dedup:
    level: DEBUG
    handlers: [console, file, phase_file]
    propagate: false
    
  yunmin.format:
    level: DEBUG
    handlers: [console, file, phase_file]
    propagate: false
    
  yunmin.dem:
    level: DEBUG
    handlers: [console, file, phase_file]
    propagate: false
    
  yunmin.evaluation:
    level: DEBUG
    handlers: [console, file, phase_file]
    propagate: false

root:
  level: INFO
  handlers: [console, file] 